/*
 * This file was generated by the mksignames program.
 */

#include "shell.h"

char *const sigmesg[32] = {
      0,
      "Hangup",
      "Interrupt",
      "Quit",
      "Illegal instruction",
      "Trace/BPT trap",
      "abort",
      0,
      "Floating exception",
      "Killed",
      "Bus error",
      "Memory fault",
      "Bad system call",
      "Broken pipe",
      "Alarm call",
      "Terminated",
      "User signal 1",
      "User signal 2",
      0,
      0,
      0,
      0,
      "Poll",
      "Stopped",
      "Stopped",
      0,
      "Stopped (input)",
      "Stopped (output)",
      "Virtual alarm",
      "Profiling alarm",
      "Time limit exceeded",
      0,
};
